
// ********RoostGPT********
/*
Test generated by RoostGPT for test Rahul-jav-test-15 using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022

ROOST_METHOD_HASH=loginUser_d19666d97a
ROOST_METHOD_SIG_HASH=loginUser_8fe76c816e

Scenario 1: Successful Login with Valid Credentials

Details:
  TestName: loginWithValidCredentials
  Description: Verify that a user can successfully login when providing correct email and password.

Execution:
  Arrange:
    - Mock UserAccRepo to return a valid User_Credentials object
    - Set up test email and matching password
  Act:
    - Call loginUser with valid email and password
  Assert:
    - Verify return value equals "Logado"

Validation:
  Ensures the login functionality works correctly when valid credentials are provided, representing the happy path scenario.

*/

// ********RoostGPT********

package com.medeiros.SPRINGProject.Controllers;

import com.medeiros.SPRINGProject.Models.*;
import com.medeiros.SPRINGProject.Security.JwtUtil;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import java.util.Objects;

@ExtendWith(MockitoExtension.class)
class AuthControllerLoginUserTest {

	@Mock
	private UserAccRepository UserAccRepo;

	@InjectMocks
	private AuthController authController;

	private User_Credentials testUser;

	@BeforeEach
	void setUp() {
		testUser = new User_Credentials("test@email.com", "password123", "testUser");
	}

	@Test
    @Tag("valid")
    void loginWithValidCredentials() {
        when(UserAccRepo.findUserByEmail("test@email.com")).thenReturn(testUser);
        String result = authController.loginUser("test@email.com", "password123");
        assertEquals("Logado", result);
        verify(UserAccRepo).findUserByEmail("test@email.com");
    }

	@Test
    @Tag("invalid")
    void loginWithIncorrectPassword() {
        when(UserAccRepo.findUserByEmail("test@email.com")).thenReturn(testUser);
        String result = authController.loginUser("test@email.com", "wrongpassword");
        assertEquals("Senha incorreta", result);
        verify(UserAccRepo).findUserByEmail("test@email.com");
    }

	@Test
    @Tag("invalid")
    void loginWithNonExistentEmail() {
        when(UserAccRepo.findUserByEmail("nonexistent@email.com")).thenReturn(null);
        String result = authController.loginUser("nonexistent@email.com", "anypassword");
        assertEquals("Email não encontrado!", result);
        verify(UserAccRepo).findUserByEmail("nonexistent@email.com");
    }

	@Test
	@Tag("boundary")
	void loginWithEmptyCredentials() {
		String result = authController.loginUser("", "");
		assertEquals("Email não encontrado!", result);
		verify(UserAccRepo).findUserByEmail("");
	}

}