
// ********RoostGPT********
/*
Test generated by RoostGPT for test Rahul-jav-test-15 using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022

ROOST_METHOD_HASH=createAuser_43c81bbbba
ROOST_METHOD_SIG_HASH=createAuser_2684b4910b

Scenario 1: Successful User Creation

Details:
  TestName: createUserWithValidCredentials
  Description: Verify that a user is successfully created when all input parameters are valid and passwords match.

Execution:
  Arrange:
    - Mock UserAccRepo and Log repositories
    - Prepare valid test data:
      email = "test@email.com"
      password = "pass123"
      confirmPassword = "pass123"
      username = "testUser"
  Act:
    - Call createAuser with the prepared test data
  Assert:
    - Verify "Sucesso" is returned
    - Verify UserAccRepo.save() was called once
    - Verify Log.save() was called once with correct log data

Validation:
  Ensures the happy path works correctly with matching passwords and valid credentials

*/

// ********RoostGPT********

package com.medeiros.SPRINGProject.Controllers;

import com.medeiros.SPRINGProject.Models.*;
import com.medeiros.SPRINGProject.Security.JwtUtil;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import java.util.Objects;

@SpringBootTest
class AuthControllerCreateAuserTest {

	@Mock
	private UserAccRepository UserAccRepo;

	@Mock
	private LogRepository Log;

	@InjectMocks
	private AuthController authController;

	@BeforeEach
	void setUp() {
		MockitoAnnotations.openMocks(this);
	}

	@Test
	@Tag("valid")
	void createUserWithValidCredentials() {
		// Arrange
		String email = "test@email.com";
		String password = "pass123";
		String confirmPassword = "pass123";
		String username = "testUser";
		// Act
		String result = authController.createAuser(email, password, confirmPassword, username);
		// Assert
		assertEquals("Sucesso", result);
		verify(UserAccRepo, times(1)).save(any(User_Credentials.class));
		verify(Log, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("invalid")
	void createUserWithMismatchedPasswords() {
		// Arrange
		String email = "test@email.com";
		String password = "pass123";
		String confirmPassword = "pass124";
		String username = "testUser";
		// Act
		String result = authController.createAuser(email, password, confirmPassword, username);
		// Assert
		assertEquals("Senhas não batem!", result);
		verify(UserAccRepo, never()).save(any(User_Credentials.class));
		verify(Log, never()).save(any(LogModel.class));
	}

	@Test
	@Tag("boundary")
	void createUserWithEmptyCredentials() {
		// Arrange
		String email = "";
		String password = "";
		String confirmPassword = "";
		String username = "";
		// Act
		String result = authController.createAuser(email, password, confirmPassword, username);
		// Assert
		assertEquals("Sucesso", result);
		verify(UserAccRepo, times(1)).save(any(User_Credentials.class));
		verify(Log, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("integration")
	void createUserAndVerifyRepositoryInteraction() {
		// Arrange
		String email = "test@email.com";
		String password = "pass123";
		String confirmPassword = "pass123";
		String username = "testUser";
		User_Credentials expectedUser = new User_Credentials(email, password, username);
		when(UserAccRepo.save(any(User_Credentials.class))).thenReturn(expectedUser);
		// Act
		String result = authController.createAuser(email, password, confirmPassword, username);
		// Assert
		assertEquals("Sucesso", result);
		verify(UserAccRepo, times(1)).save(argThat(user -> user.getEmail().equals(email)
				&& user.getPassword().equals(password) && user.getUsername().equals(username)));
	}

}