
// ********RoostGPT********
/*
Test generated by RoostGPT for test Rahul-jav-test-15 using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022

ROOST_METHOD_HASH=newToken_0b98d9bf3a
ROOST_METHOD_SIG_HASH=newToken_275af2b2e1

Scenario 1: Successful JWT Token Generation

Details:
  TestName: generateValidToken
  Description: Verify that a valid JWT token is generated when provided with valid authentication credentials.

Execution:
  Arrange:
    - Create mock Authentication object
    - Setup User_Credentials with valid username
    - Configure jwtSecret and jwtExpirationMilliseg
  Act:
    - Call newToken(authentication)
  Assert:
    - Verify returned token is not null
    - Verify token structure is valid JWT format

Validation:
  Ensures the method successfully generates a JWT token containing the user's username,
  proper expiration time, and valid signature using the secret key.


*/

// ********RoostGPT********

package com.medeiros.SPRINGProject.Security;

import com.medeiros.SPRINGProject.Models.User_Credentials;
import io.jsonwebtoken.Jwts;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.security.core.Authentication;
import org.springframework.test.util.ReflectionTestUtils;
import java.util.Base64;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.when;
import org.junit.jupiter.api.*;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import java.nio.charset.StandardCharsets;
import java.security.Key;
import java.util.Date;

class JwtUtilNewTokenTest {

	private JwtUtil jwtUtil;

	@Mock
	private Authentication authentication;

	@Mock
	private User_Credentials userCredentials;

	@BeforeEach
	void setUp() {
		MockitoAnnotations.openMocks(this);
		jwtUtil = new JwtUtil();
		ReflectionTestUtils.setField(jwtUtil, "jwtSecret", "testSecretKey12345678901234567890");
		ReflectionTestUtils.setField(jwtUtil, "jwtExpirationMilliseg", 3600000L);
	}

	@Test
	@Tag("valid")
	void generateValidToken() {
		// Arrange
		String username = "testuser@example.com";
		when(authentication.getPrincipal()).thenReturn(userCredentials);
		when(userCredentials.getUsername()).thenReturn(username);
		// Act
		String token = jwtUtil.newToken(authentication);
		// Assert
		assertNotNull(token);
		assertTrue(token.split("\\.").length == 3); // Verify JWT structure
													// (header.payload.signature)

		// Decode and verify payload contains username
		String payload = new String(Base64.getDecoder().decode(token.split("\\.")[1]));
		assertTrue(payload.contains(username));
	}

	@Test
	@Tag("invalid")
	void generateTokenWithNullAuthentication() {
		// Act & Assert
		assertNull(jwtUtil.newToken(null));
	}

	@Test
    @Tag("invalid")
    void generateTokenWithNullPrincipal() {
        // Arrange
        when(authentication.getPrincipal()).thenReturn(null);
        // Act & Assert
        assertThrows(NullPointerException.class, () -> jwtUtil.newToken(authentication));
    }

	@Test
    @Tag("boundary")
    void generateTokenWithEmptyUsername() {
        // Arrange
        when(authentication.getPrincipal()).thenReturn(userCredentials);
        when(userCredentials.getUsername()).thenReturn("");
        // Act
        String token = jwtUtil.newToken(authentication);
        // Assert
        assertNotNull(token);
        assertTrue(token.split("\\.").length == 3);
    }

}