
// ********RoostGPT********
/*
Test generated by RoostGPT for test Rahul-jav-test-15 using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022

ROOST_METHOD_HASH=getUserName_2f305a5b83
ROOST_METHOD_SIG_HASH=getUserName_e910087e84

Scenario 1: Valid Token Returns Username Successfully

Details:
  TestName: validTokenReturnsUsername
  Description: Verify that when a valid JWT token is provided, the method returns the correct username from the token's claims.

Execution:
  Arrange:
    - Create authentication with valid user credentials
    - Generate a valid token using newToken() method
  Act:
    - Call getUserName() with the valid token
  Assert:
    - Verify returned username matches the original username

Validation:
  Ensures the method correctly extracts and returns the subject (username) from a valid token's claims, demonstrating proper token parsing and claim extraction.


*/

// ********RoostGPT********

package com.medeiros.SPRINGProject.Security;

import com.medeiros.SPRINGProject.Models.User_Credentials;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.security.core.Authentication;
import org.springframework.test.util.ReflectionTestUtils;
import java.nio.charset.StandardCharsets;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.when;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import java.security.Key;
import java.util.Date;

class JwtUtilGetUserNameTest {

	private JwtUtil jwtUtil;

	@Mock
	private Authentication authentication;

	@BeforeEach
	void setUp() {
		MockitoAnnotations.openMocks(this);
		jwtUtil = new JwtUtil();
		ReflectionTestUtils.setField(jwtUtil, "jwtSecret", "testSecretKey123testSecretKey123testSecretKey123");
		ReflectionTestUtils.setField(jwtUtil, "jwtExpirationMilliseg", 3600000L);
	}

	@Test
	@Tag("valid")
	void validTokenReturnsUsername() {
		// Arrange
		User_Credentials userCredentials = new User_Credentials();
		userCredentials.setUsername("testuser@example.com");
		when(authentication.getPrincipal()).thenReturn(userCredentials);

		String token = jwtUtil.newToken(authentication);
		// Act
		String extractedUsername = jwtUtil.getUserName(token);
		// Assert
		assertEquals("testuser@example.com", extractedUsername);
	}

	@Test
	@Tag("invalid")
	void invalidTokenReturnsNull() {
		// Act
		String extractedUsername = jwtUtil.getUserName("invalid.token.string");
		// Assert
		assertNull(extractedUsername);
	}

	@Test
	@Tag("boundary")
	void emptyTokenReturnsNull() {
		// Act
		String extractedUsername = jwtUtil.getUserName("");
		// Assert
		assertNull(extractedUsername);
	}

	@Test
	@Tag("invalid")
	void nullTokenReturnsNull() {
		// Act
		String extractedUsername = jwtUtil.getUserName(null);
		// Assert
		assertNull(extractedUsername);
	}

	@Test
	@Tag("boundary")
	void malformedTokenReturnsNull() {
		// Act
		String extractedUsername = jwtUtil.getUserName("invalid.token");
		// Assert
		assertNull(extractedUsername);
	}

}